# Generated by Django 4.2.4 on 2023-09-04 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
    ]
