# Generated by Django 4.2.4 on 2023-09-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_remove_project_is_completed_remove_task_is_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("depiction", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="funds_used",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="progress",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="tasks.projectcategory",
            ),
        ),
    ]
