# Generated by Django 4.2.4 on 2023-09-17 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_project_project_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskEvaluation",
            new_name="WorkerEvaluation",
        ),
    ]
