# Generated by Django 4.2.4 on 2023-09-18 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_rename_taskevaluation_workerevaluation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
    ]
