# Generated by Django 4.2.4 on 2023-09-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_task_project_projectblock_task_block"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="projects", to="tasks.team"
            ),
        ),
    ]
