# Generated by Django 4.2.4 on 2023-09-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_remove_project_team_project_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="team",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="tasks.team"
            ),
        ),
        migrations.RemoveField(
            model_name="worker",
            name="team",
        ),
        migrations.AddField(
            model_name="worker",
            name="team",
            field=models.ManyToManyField(
                blank=True, related_name="workers", to="tasks.team"
            ),
        ),
    ]
